apiVersion: apps/v1
kind: Deployment
metadata:
  name: brms-frontend
  labels:
    app.kubernetes.io/name: brms-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: brms-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: brms-frontend
    spec:
      containers:
        - name: brms-frontend
          image: '{{ .Values.image.tag }}'
          ports:
            - containerPort: 8080
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
