apiVersion: apps/v1
kind: Deployment
metadata:
  name: brm-app
  labels:
    app.kubernetes.io/name: brm-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: brm-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: brm-app
      annotations:
        helm.sh/release: "{{ .Release.Name }}"
        helm.sh/revision: "{{ .Release.Revision }}"
    spec:
      containers:
        - name: brm-app
          image: '{{ .Values.image.tag }}'
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 150m
              memory: 512Mi
            requests:
              cpu: 75m
              memory: 350Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
