apiVersion: v1
kind: Service
metadata:
  name: brm-app
  labels:
    app.kubernetes.io/name: brm-app
spec:
  selector:
    app.kubernetes.io/name: brm-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080