apiVersion: v1
kind: Service
metadata:
  name: brms-frontend
  labels:
    app.kubernetes.io/name: brms-frontend
spec:
  selector:
    app.kubernetes.io/name: brms-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080